apiVersion: v1
kind: Pod
metadata:
  name: wc
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: wc
    image: martindocker22/nbapc:crawler
    imagePullPolicy: Always
    volumeMounts:
            - mountPath: /dev/shm
              name: dshm
    env:
    - name: table
      value: boxscores
    - name: season
      value: 2018-19
    - name: filesystem
      value: wasb