apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wc
  name: wc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wc
  template:
    metadata:
      labels:
        app: wc
      name: wc
    spec:
      containers:
      - name: wc
        image: nbapc.azurecr.io/nbacrawler:latest
        env:
        - name: table
          value: ##table##
        - name: season
          value: ##season##
        - name: filesystem
          value: ##filesystem##
        - name: wasbaccountname
          value: ##wasbaccountname##
        - name: wasbaccountkey
          value: ##wasbaccountkey##